### ISSUE TITLE
对于电视能实现换台和音量吗

### ISSUE THREAD

**Issue by fakers777** [c1pher-cn/tmall-bot-x1#1]
对于电视能实现换台和音量吗

**Comment by c1pher-cn** [comment]
我的代码目前没有关于换台和调音量的，协议转换有点麻烦暂时没时间研究，另外我家的电视也不需要换台没有测试条件（要机顶盒换台），但天猫精灵的api是支持的。

**Comment by RayzzzzzZ** [comment]
设备列表的JSON数据，“键”不带双引号也可以的？话说有没遇到提交AUTHORIZE后会显示参数错误

**Comment by c1pher-cn** [comment]
https://bbs.hassbian.com/thread-3881-1-1.html  已实现基于该方式的换台
