### ISSUE TITLE
添加虚拟设备一直显示添加失败，数据库确认是正确的

### ISSUE THREAD

**Issue by zhangzhizhilong** [c1pher-cn/tmall-bot-x1#10]
添加虚拟设备一直显示添加失败，数据库确认是正确的，求解答可能是什么原因

**Comment by sixmoonriver** [comment]
insert into oauth_devices(user_id,deviceName,deviceId,jsonData,virtual,devices) values('10001','light','10002','','0','light');
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'virtual,devices) values('10001','light','10002','','0','light')' at line 1

我也遇到类似的问题，直接在数据里面模拟执行语句，报这个错，最后也改了代码。
server.php 第57行，改为这个：
        $stm = $db->prepare("update oauth_devices set (deviceName=:deviceName,jsonData=:jsonData,`virtual`=:virtual,devices=:devices)  where user_id=:user_id and deviceId=:deviceId)");
server.php第90行，改为这个
 $stm = $db->prepare("insert into oauth_devices (user_id,deviceName,deviceId,jsonData,`virtual`,devices)  values(:user_id,:deviceName,:deviceId,:jsonData,:virtual,:devices)");
添加设备成功，mysql5.7.22
汗，这个‘`'竟然被转义了。

**Comment by c1pher-cn** [comment]
> 添加虚拟设备一直显示添加失败，数据库确认是正确的，求解答可能是什么原因

没有上下文，猜不出你的问题

**Comment by c1pher-cn** [comment]
> server.php

看不出来你改了啥，说清楚点?
目前看只有特殊的mysql版本有问题，大部分是没问题的

**Comment by zhangzhizhilong** [comment]
> insert into oauth_devices(user_id,deviceName,deviceId,jsonData,virtual,devices) values('10001','light','10002','','0','light');
> ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'virtual,devices) values('10001','light','10002','','0','light')' at line 1
> 
> 我也遇到类似的问题，直接在数据里面模拟执行语句，报这个错，最后也改了代码。
> server.php 第57行，改为这个：
> $stm = $db->prepare("update oauth_devices set (deviceName=:deviceName,jsonData=:jsonData,`virtual`=:virtual,devices=:devices) where user_id=:user_id and deviceId=:deviceId)");
> server.php第90行，改为这个
> $stm = $db->prepare("insert into oauth_devices (user_id,deviceName,deviceId,jsonData,`virtual`,devices) values(:user_id,:deviceName,:deviceId,:jsonData,:virtual,:devices)");
> 添加设备成功，mysql5.7.22
谢谢回复，但未能解决问题，这两句代码改之前就是这样的，我的mysql版本是5.7.24，不过应该是操作数据库失败了，查看数据库表没有任何变化

**Comment by zhangzhizhilong** [comment]
> > server.php
> 
> 看不出来你改了啥，说清楚点?
> 目前看只有特殊的mysql版本有问题，大部分是没问题的
代码除了数据库名用户名和密码其他的都没改，不太会php的调试，所以我也不太清楚是什么问题，mysql版本是5.7.24

**Comment by zhangzhizhilong** [comment]
> > server.php
> 
> 看不出来你改了啥，说清楚点?
> 目前看只有特殊的mysql版本有问题，大部分是没问题的

把server.php第90行，改为这个
$stm = $db->prepare("insert into oauth_devices (user_id,deviceName,deviceId,jsonData,virtual,devices) values(:user_id,:deviceName,:deviceId,:jsonData,:virtual,:devices)");中virtual和值都去掉就能添加成功了

**Comment by zhangzhizhilong** [comment]
找到问题了virtual是mysql5.7的新关键字，所以会出问题
