### ISSUE TITLE
token返回不正确，提示3秒后返回设备列表！

### ISSUE THREAD

**Issue by xuhongv** [c1pher-cn/tmall-bot-x1#11]
- 看了这里的 '''issue''' ，我也修改那个 oauth2 的 server.php 文件的 'require_exact_redirect_uri' => false,都是这提示！最好我去调试下代码，发现 oauthorize.php 的 获取session 为空，导致调用handleAuthorizeRequest()传入参数也为空！

` $_SESSION['userinfo']['user_id']` 为空 。。。 我的是 linux + nginx +mysql5.6 + php5.6环境！

**Comment by xuhongv** [comment]
请问有什么解决方法吗

**Comment by c1pher-cn** [comment]
先访问information.php看看 session正常不，第一次应该会’注册‘一下，才会有userid

**Comment by xuhongv** [comment]
首先感谢回复！！我已经解决，不是 session 问题！应该是 php 版本问题，我换成了 php7.0完美解决了！而且我不传 user_id字段也可以返回token正确！因为oauthorize.php中传进$_SESSION['userinfo']['user_id'] 无非就是为了绑定 token和user_id关系！

**Comment by c1pher-cn** [comment]
ok 那可能还是版本差异的问题，没有条件测太多版本
