### ISSUE TITLE
对接求助

### ISSUE THREAD

**Issue by GeekAudio** [c1pher-cn/tmall-bot-x1#12]
现在好像没有办法对接了，需要api密码，但是新版hass 没有这个了。

**Comment by GeekAudio** [comment]
请检查您的homeassistant密码是否正确或自行验证下方链接是否可以打开您的HomeAssistant， 链接：
点击链接检查是否可以正常打开

**Comment by c1pher-cn** [comment]
我博客里已经更新了如何使用长效token的方法，认真看一下

深圳房大叔 <notifications@github.com> 于2019年4月16日周二 下午9:33写道：
