### ISSUE TITLE
Oauth认证无法通过

### ISSUE THREAD

**Issue by xinghusp** [c1pher-cn/tmall-bot-x1#2]
提示The redirect URI is missing or do not match, 3秒后返回设备列表。error_log记录下来的redirect_uri正确，数据库中oauth_clients的记录也正确，非常费解。。

**Comment by xinghusp** [comment]
研究了好久，发现通过以下修改可以解决这个问题
1、修改authorize.php,注释掉
$m=$request->query['redirect_uri']; 
$temp = substr($m,0,strpos($m,"?"));
$request->query['redirect_uri']= $temp; 

将$return = urldecode($m)."&code=".$code;  修改为 $return = $request->query['redirect_uri']."&code=".$code;

2、修改Oauth2-PHP-Server的相关文件。
将oauth2-server-php/src/OAuth2中的Server.php中的require_exact_redirect_uri参数改为false

这样即可。初步判定是由于oauth2server更新导致的故障，还请作者 验证~
@c1pher-cn

**Comment by c1pher-cn** [comment]
恩，也受到了别人的反馈，只是一直没时间更新代码，我是在token.php这样改的，与你的思路一样
$m=$_POST['redirect_uri'];
$temp = substr($m,0,strpos($m,"?"));
$_POST['redirect_uri']= $temp;

**Comment by sonwa** [comment]
试了两位大神的方法还是认证不通过，请问要怎样修改才行？

**Comment by c1pher-cn** [comment]
你修改了哪些

2018-05-15 16:35 GMT+08:00 SonWa <notifications@github.com>:

**Comment by c1pher-cn** [comment]
这里如果出现："Oauth token 返回不正确,请检查”或”参数值内容错误。，三秒后返回设备列表“
试一下把token.php 里这五行注释掉
$_POST['grant_type']=$_GET['grant_type'];
$_POST['code']=$_GET['code'];
$_POST['redirect_uri']=$_GET['redirect_uri'];
$_POST['client_id']=$_GET['client_id'];
$_POST['client_secret']=$_GET['client_secret'];

继续在第15行前面加这个三行
$m=$_POST['redirect_uri'];
$temp = substr($m,0,strpos($m,"?"));
$_POST['redirect_uri']= $temp;

修改Oauth2-PHP-Server的相关文件。
将oauth2-server-php/src/OAuth2中的Server.php中的require_exact_redirect_uri参数改为false
