### ISSUE TITLE
OAuth认证不行

### ISSUE THREAD

**Issue by sonwa** [c1pher-cn/tmall-bot-x1#3]
提示“调用会员中心授权验证失败, 3秒后返回设备列表”。oauth_authorization_codes表已经有生成的authorization_code了。我有post测试工具填authorization_code可以生成到oauth_access_tokens 的token的。请问是那里出问题了？

**Comment by c1pher-cn** [comment]
试一下把token.php 里这五行注释掉
$_POST['grant_type']=$_GET['grant_type'];
$_POST['code']=$_GET['code'];
$_POST['redirect_uri']=$_GET['redirect_uri'];
$_POST['client_id']=$_GET['client_id'];
$_POST['client_secret']=$_GET['client_secret'];

继续在第15行前面加这个三行
$m=$_POST['redirect_uri'];
$temp = substr($m,0,strpos($m,"?"));
$_POST['redirect_uri']= $temp;

修改Oauth2-PHP-Server的相关文件。
将oauth2-server-php/src/OAuth2中的Server.php中的require_exact_redirect_uri参数改为false

**Comment by lightfinal** [comment]
@sonwa 有没有检查下 HTTPS 的证书是否合法，如果是自己签的就会出现验证失败的错误

**Comment by sonwa** [comment]
@c1pher-cn 改了你说这个可以了。

@lightfinal 证书是在服务商生成的免费一年有效证书。
