### ISSUE TITLE
外部服务器异常提示3秒后返回设备列表

### ISSUE THREAD

**Issue by gexing147** [c1pher-cn/tmall-bot-x1#5]
根据教程搭建相关环境后，授权后提示外部服务器异常提示3秒后返回设备列表，请问我是哪里出了问题

**Comment by c1pher-cn** [comment]
修改Oauth2-PHP-Server的相关文件。
将oauth2-server-php/src/OAuth2中的Server.php中的require_exact_redirect_uri参数改为false

代码用的最新的吗？

**Comment by felix-fei-fei** [comment]
@gexing147 你可以确认下php的log，看下有无异常。
