### ISSUE TITLE
因为不是撸PHP的，我刚刚部署了你的代码 CALLBACK.PHP  UID未声明

### ISSUE THREAD

**Issue by Zendic** [c1pher-cn/tmall-bot-x1#8]
看起来这个CALLBACK.PHP像是用户做登录的，直接往SESSION写入一个用户，然后跳转到 information.php？跳转后提示 “POST为空c1pher001” 求帮助

**Comment by c1pher-cn** [comment]
POST为空c1pher001 只是我调试时的记录，不影响，你自己写入session这个就不在我的处理范围了
