### ISSUE TITLE
homeassistant 改了认证方式后，API密码要如何弄

### ISSUE THREAD

**Issue by sixmoonriver** [c1pher-cn/tmall-bot-x1#9]
如题，新的homeassistant改了认证方式，支持长期的token，有没有办法可以支持，不太懂PHP

**Comment by bingbing0809** [comment]
我也是菜鸟，不懂




| |
陈
|
|
邮箱：chenbo-20010809@163.com
|

签名由 网易邮箱大师 定制

在2018年11月29日 18:46，sixmoonriver 写道：

如题，新的homeassistant改了认证方式，支持长期的token，有没有办法可以支持，不太懂PHP

**Comment by c1pher-cn** [comment]
> 如题，新的homeassistant改了认证方式，支持长期的token，有没有办法可以支持，不太懂PHP

我已经更新支持了最新的认真方式，文档看一下？
